const mongoose = require("mongoose");

// SCORE SCHEMA
const score = new mongoose.Schema( {
  
  
        firstname: String,
        lastname: String,
        code: String,
        score: String,
        examname: String,
        questionnumber: String,
        examtime: String,
        
        questionchoose1 : String,
        questionchoose2 : String,
        questionchoose3 : String,
        questionchoose4 : String,
        questionchoose5 : String,
        questionchoose6 : String,
        questionchoose7 : String,
        questionchoose8 : String,
        questionchoose9 : String,
        questionchoose10 : String,
        questionchoose11 : String,
        questionchoose12 : String,
        questionchoose13 : String,
        questionchoose14 : String,
        questionchoose15 : String,
        questionchoose16 : String,
        questionchoose17 : String,
        questionchoose18 : String,
        questionchoose19 : String,
        questionchoose20 : String,

        answerc1 : String,
        answerc2 : String,
        answerc3 : String,
        answerc4 : String,
        answerc5 : String,
        answerc6 : String,
        answerc7 : String,
        answerc8 : String,
        answerc9 : String,
        answerc10 : String,
        answerc11 : String,
        answerc12 : String,
        answerc13 : String,
        answerc14 : String,
        answerc15 : String,
        answerc16 : String,
        answerc17 : String,
        answerc18 : String,
        answerc19 : String,
        answerc20 : String,

        resultchoose1 : String,
        resultchoose2 : String,
        resultchoose3 : String,
        resultchoose4 : String,
        resultchoose5 : String,
        resultchoose6 : String,
        resultchoose7 : String,
        resultchoose8 : String,
        resultchoose9 : String,
        resultchoose10 : String,
        resultchoose11: String,
        resultchoose12: String,
        resultchoose13: String,
        resultchoose14: String,
        resultchoose15: String,
        resultchoose16: String,
        resultchoose17: String,
        resultchoose18: String,
        resultchoose19: String,
        resultchoose20: String,
        
        questionassy1 : String,
        questionassy2 : String,
        questionassy3 : String,
        questionassy4 : String,
        questionassy5 : String,
        questionassy6 : String,
        questionassy7 : String,
        questionassy8 : String,
        questionassy9 : String,
        questionassy10 : String,
        questionassy11 : String,
        questionassy12 : String,
        questionassy13 : String,
        questionassy14 : String,
        questionassy15 : String,
        questionassy16 : String,
        questionassy17 : String,
        questionassy18 : String,
        questionassy19 : String,
        questionassy20 : String,

        answerassy1 : String,
        answerassy2 : String,
        answerassy3 : String,
        answerassy4 : String,
        answerassy5 : String,
        answerassy6 : String,
        answerassy7 : String,
        answerassy8 : String,
        answerassy9 : String,
        answerassy10 : String,
        answerassy11 : String,
        answerassy12 : String,
        answerassy13 : String,
        answerassy14 : String,
        answerassy15 : String,
        answerassy16 : String,
        answerassy17 : String,
        answerassy18 : String,
        answerassy19 : String,
        answerassy20 : String,

        resultassy1 : String,
        resultassy2 : String,
        resultassy3 : String,
        resultassy4 : String,
        resultassy5 : String,
        resultassy6 : String,
        resultassy7 : String,
        resultassy8 : String,
        resultassy9 : String,
        resultassy10 : String,
        resultassy11: String,
        resultassy12: String,
        resultassy13: String,
        resultassy14: String,
        resultassy15: String,
        resultassy16: String,
        resultassy17: String,
        resultassy18: String,
        resultassy19: String,
        resultassy20: String,

        questioncomplete1 : String,
        questioncomplete2 : String,
        questioncomplete3 : String,
        questioncomplete4 : String,
        questioncomplete5 : String,
        questioncomplete6 : String,
        questioncomplete7 : String,
        questioncomplete8 : String,
        questioncomplete9 : String,
        questioncomplete10 : String,
        questioncomplete11 : String,
        questioncomplete12 : String,
        questioncomplete13 : String,
        questioncomplete14 : String,
        questioncomplete15 : String,
        questioncomplete16 : String,
        questioncomplete17 : String,
        questioncomplete18 : String,
        questioncomplete19 : String,
        questioncomplete20 : String,

        answercomplete1 : String,
        answercomplete2 : String,
        answercomplete3 : String,
        answercomplete4 : String,
        answercomplete5 : String,
        answercomplete6 : String,
        answercomplete7 : String,
        answercomplete8 : String,
        answercomplete9 : String,
        answercomplete10 : String,
        answercomplete11 : String,
        answercomplete12 : String,
        answercomplete13 : String,
        answercomplete14 : String,
        answercomplete15 : String,
        answercomplete16 : String,
        answercomplete17 : String,
        answercomplete18 : String,
        answercomplete19 : String,
        answercomplete20 : String,

        resultcomplete1 : String,
        resultcomplete2 : String,
        resultcomplete3 : String,
        resultcomplete4 : String,
        resultcomplete5 : String,
        resultcomplete6 : String,
        resultcomplete7 : String,
        resultcomplete8 : String,
        resultcomplete9 : String,
        resultcomplete10 : String,
        resultcomplete11: String,
        resultcomplete12: String,
        resultcomplete13: String,
        resultcomplete14: String,
        resultcomplete15: String,
        resultcomplete16: String,
        resultcomplete17: String,
        resultcomplete18: String,
        resultcomplete19: String,
        resultcomplete20: String,

        questiontf1 : String,
        questiontf2 : String,
        questiontf3 : String,
        questiontf4 : String,
        questiontf5 : String,
        questiontf6 : String,
        questiontf7 : String,
        questiontf8 : String,
        questiontf9 : String,
        questiontf10 : String,
        questiontf11 : String,
        questiontf12 : String,
        questiontf13 : String,
        questiontf14 : String,
        questiontf15 : String,
        questiontf16 : String,
        questiontf17 : String,
        questiontf18 : String,
        questiontf19 : String,
        questiontf20 : String,

        answertf1 : String,
        answertf2 : String,
        answertf3 : String,
        answertf4 : String,
        answertf5 : String,
        answertf6 : String,
        answertf7 : String,
        answertf8 : String,
        answertf9 : String,
        answertf10 : String,
        answertf11 : String,
        answertf12 : String,
        answertf13 : String,
        answertf14 : String,
        answertf15 : String,
        answertf16 : String,
        answertf17 : String,
        answertf18 : String,
        answertf19 : String,
        answertf20 : String,

        resulttruefalse1 : String,
        resulttruefalse2 : String,
        resulttruefalse3 : String,
        resulttruefalse4 : String,
        resulttruefalse5 : String,
        resulttruefalse6 : String,
        resulttruefalse7 : String,
        resulttruefalse8 : String,
        resulttruefalse9 : String,
        resulttruefalse10 : String,
        resulttruefalse11: String,
        resulttruefalse12: String,
        resulttruefalse13: String,
        resulttruefalse14: String,
        resulttruefalse15: String,
        resulttruefalse16: String,
        resulttruefalse17: String,
        resulttruefalse18: String,
        resulttruefalse19: String,
        resulttruefalse20: String,
      },  
  { timestamps: true }
);

const Score = mongoose.model("Score", score);

module.exports = Score;
